# This file is included in-line in the env section of deployment.yaml
# if .Values.generatedBindings.enabled is true.
- name: IBM_APM_SERVER_URL
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_server_url
      optional: true
- name: IBM_APM_KEYFILE
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_keyfile
      optional: true
- name: IBM_APM_KEYFILE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_keyfile_password
      optional: true
- name: IBM_APM_INGRESS_URL
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_ingress_url
      optional: true
- name: IBM_APM_ACCESS_TOKEN
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_access_token
      optional: true
- name: MONGO_USER
  valueFrom:
    secretKeyRef:
      name: mongodbenv
      key: mongo_user
      optional: false
- name: MONGO_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mongodbenv
      key: mongo_password
      optional: false
- name: MONGO_DATABASE
  valueFrom:
    secretKeyRef:
      name: mongodbenv
      key: mongo_database
      optional: false
- name: MONGO_COLLECTION
  valueFrom:
    secretKeyRef:
      name: mongodbenv
      key: mongo_collection
      optional: false
- name: MONGO_IP
  valueFrom:
    secretKeyRef:
      name: mongodbenv
      key: mongo_ip
      optional: false
- name: MONGO_PORT
  valueFrom:
    secretKeyRef:
      name: mongodbenv
      key: mongo_port
      optional: false
- name: TOPIC
  valueFrom:
    secretKeyRef:
      name: trade-history-kafka
      key: topic
      optional: true
- name: BOOTSTRAP_SERVER
  valueFrom:
    secretKeyRef:
      name: trade-history-kafka
      key: url
      optional: true
- name: CONSUMER_API_KEY
  valueFrom:
    secretKeyRef:
      name: trade-history-kafka
      key: apikey
      optional: true
- name: KAFKA_KEYSTORE
  valueFrom:
    secretKeyRef:
      name: trade-history-kafka
      key: keystore
      optional: true
- name: JWT_AUDIENCE
  valueFrom:
    secretKeyRef:
      name: jwt 
      key: audience
- name: JWT_ISSUER
  valueFrom:
    secretKeyRef:
      name: jwt       
      key: issuer